# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib
	fib_array = [1,2]

	count = 0
	loop do count
		fib_array << fib_array[count] + fib_array[count +1]
		count += 1
		break if fib_array[count] > 4000000
	end
	fib_array.select {|int| int.even?}.reduce(:+)
end
p fib
